version: '3.3'

services:
  db:
    image: postgres
    networks:
      - ngr-network
    env_file: .env.dev
    volumes: 
      - ngr_db:/var/lib/postgresql/data 

  ngr_website:
    build:
      context: ./ngr_website
      dockerfile: Dockerfile
    networks:
      - ngr-network
    volumes:
      - ngr_staticfiles:/usr/src/app/staticfiles
      - ngr_media:/usr/src/app/media
    env_file: .env.dev
    depends_on:
      - db

  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: ./nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    networks:
      - ngr-network
    volumes:
      - ngr_staticfiles:/usr/src/app/staticfiles
      - ngr_media:/usr/src/app/media
    depends_on:
      - ngr_website

volumes:
  ngr_db:
  ngr_staticfiles:
  ngr_media:

networks:
  ngr-network:
    driver: bridge

