version: '3.3'

services:
  ngr_website:
    build:
      context: ./ngr_website
      cache_from:
        - "${NGR_IMAGE}"
    image: "${NGR_IMAGE}"
    networks:
      - ngr-network
    volumes:
      - ngr_staticfiles:/usr/src/app/staticfiles
      - ngr_media:/usr/src/app/media
    depends_on:
      - db
    env_file: .env

  db:
    build:
      context: ./postgres
      cache_from:
        - "${POSTGRES_IMAGE}"
    image: "${POSTGRES_IMAGE}"
    networks:
      - ngr-network
    env_file: .env
    volumes: 
      - ngr_db:/var/lib/postgresql/data 

  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    ports:
      - 443:443
      - 80:80
    networks:
      - ngr-network
    volumes:
      - ngr_staticfiles:/usr/src/app/staticfiles
      - ngr_media:/usr/src/app/media
    depends_on:
      - ngr_website

volumes:
  ngr_db:
  ngr_staticfiles:
  ngr_media:

networks:
  ngr-network:
    driver: bridge

