version: '3.3'

services:
  db:
    image: postgres
    networks:
      - ngr-network
    env_file: .env.dev
    volumes: 
      - ngr_db:/var/lib/postgresql/data 

  ngr_website:
    build:
      context: ./ngr_website
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    networks:
      - ngr-network
    volumes:
      - ./ngr_website/:/usr/src/app/
      - ngr_staticfiles:/usr/src/app/staticfiles
      - ngr_media:/usr/src/app/media
    env_file: .env.dev
    depends_on:
      - db

volumes:
  ngr_db:
  ngr_staticfiles:
  ngr_media:

networks:
  ngr-network:
    driver: bridge

