# Generated by Django 3.2.6 on 2021-08-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='thumbnail',
        ),
    ]
