# Generated by Django 3.2.6 on 2021-08-19 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20210817_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestant',
            old_name='agree_to_payment_of_registrtion_fee',
            new_name='i_hereby_agree_that_the_information_provided_above_is_accurate',
        ),
        migrations.RenameField(
            model_name='contestant',
            old_name='agree_to_provision_of_accurate_information',
            new_name='i_hereby_agree_to_pay_the_registration_fee',
        ),
        migrations.RenameField(
            model_name='contestant',
            old_name='agree_to_terms_and_conditions',
            new_name='i_hereby_agree_to_the_terms_and_conditions',
        ),
        migrations.AddField(
            model_name='contest',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='about',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be 11 digits and entered in the format: '080**'.", regex='^0\\d{1}0\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='ref_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='sex',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='state',
            field=models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('FCT - Abuja', 'FCT - Abuja'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], default='Lagos', max_length=200),
        ),
    ]
