# Generated by Django 3.2.6 on 2021-08-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20210819_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
