# Generated by Django 3.2.6 on 2021-11-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20211019_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
