# Generated by Django 3.2.6 on 2021-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_contestant_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='i_hereby_agree_that_the_information_provided_above_is_accurate',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='i_hereby_agree_to_pay_the_registration_fee',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='i_hereby_agree_to_the_terms_and_conditions',
        ),
        migrations.AddField(
            model_name='contestant',
            name='agree_that_the_information_provided_is_accurate',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contestant',
            name='agree_to_pay_the_registration_fee',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contestant',
            name='agree_to_the_terms_and_conditions',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestant',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
