# Generated by Django 3.2.6 on 2021-12-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_contest_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='votes_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
