# Generated by Django 3.2.6 on 2021-08-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20210819_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='photograph',
            field=models.ImageField(upload_to='media/photograph/'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='ref_number',
            field=models.CharField(default=12312312, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestant',
            name='slug',
            field=models.SlugField(),
        ),
    ]
