# Generated by Django 3.2.6 on 2021-08-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20210821_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
