# Generated by Django 3.2.6 on 2021-12-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_alter_vote_votes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='votes_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
