# Generated by Django 3.2.6 on 2021-08-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_alter_contestant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='photograph',
            field=models.ImageField(upload_to='photograph/'),
        ),
    ]
